[package]
name = "directedtype"
version = "0.1.0"
edition = "2021"
description = "A pure functional reactive layout engine based on a Directed Acyclic Graph (DAG) of layout equations"
license = "MIT OR Apache-2.0"

[dependencies]
image = "0.25.10"
logos = "0.14"
notify = "8.2.0"
objc2 = "0.5.2"
parley = "0.11.1"
pollster = "1.0.1"
raw-window-handle = "0.6.2"
thiserror = "2.0"
vello = "0.10.0"
winit = "0.30.13"

[dev-dependencies]
pretty_assertions = "1.4"
